# Generated by Django 4.0.6 on 2024-04-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacientifica',
            old_name='codigo_cnaf',
            new_name='codigo_cnaef',
        ),
    ]
