# Generated by Django 4.0.6 on 2024-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_rename_codigo_cnaf_areacientifica_codigo_cnaef'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo_curso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
