# Generated by Django 4.0.6 on 2024-04-07 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_musica_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ano_criado',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banda',
            name='ano_criado',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='ano_criado',
            field=models.IntegerField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.DurationField(default=datetime.timedelta(seconds=1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
